### ISSUE TITLE
Apache 2 Licence Breach

### ISSUE THREAD

**Issue by H0R5E** [tverbrug/openWEC#1]
Hi, I believe you are in breach of the Apache 2 licence used for Nemoh. It particular it states:

> 1. Redistribution. You may reproduce and distribute copies of the Work or Derivative Works thereof in any medium, with or without modifications, and in Source or Object form, provided that You meet the following conditions:
>    
>    You must give any other recipients of the Work or Derivative Works a copy of this License; and
>    ...

**Comment by tverbrug** [comment]
Thank you very much for noticing, I did not think about this. I have added a copy of the license to the folder! Kind regards

**Comment by H0R5E** [comment]
No problem! If I were you I would put it into the Nemoh folder and then consider how you want to licence your own code.

For instance, a US citizen could not legally use your work without you providing an explicit licence for them to do so. If you need some help, here is an easy guide to choosing a licence:

http://choosealicense.com/

**Comment by H0R5E** [comment]
I should say that you probably **must** choose GPL v3, because you are using the open source version of Qt. It has this type of licence and it is infectious, so your work should be licenced the same way.

See the top answer to this:

http://askubuntu.com/questions/339723/can-i-sell-my-pyqt4-app-without-having-a-pyqt-license

**Comment by tverbrug** [comment]
Hi!

I have selected the GPL v3 as License and updated it in the github files! Thank you again for all your help!

**Comment by H0R5E** [comment]
No problem. Ill close the bug.
